using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Net.Mime;
using System.Threading.Tasks;

using gamon;
using GlucoMan;
using GlucoMan.Maui;
using GlucoMan.Maui.Resources;
using GlucoMan.Maui.Resources.Strings;
using Microsoft.Maui;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Devices;
using Microsoft.Maui.Storage;
using NUnit.Framework;

namespace GlucoMan.Maui.UnitTests;




/// <summary>
/// Unit tests for StatisticsAndGraphPage.
/// </summary>
public partial class StatisticsAndGraphPageTests
{
    /// <summary>
    /// Tests that the StatisticsAndGraphPage constructor successfully initializes.
    /// NOTE: This test requires the MAUI runtime and XAML infrastructure to be available.
    /// The constructor calls InitializeComponent() which processes XAML and initializes UI controls.
    /// If this test fails with initialization errors, it may require running as a MAUI UI test
    /// rather than a standard unit test.
    /// </summary>
    [Test]
    public void Constructor_WhenCalled_InitializesSuccessfully()
    {
        // Arrange & Act
        StatisticsAndGraphPage? page = null;
        TestDelegate act = () => page = new StatisticsAndGraphPage();

        // Assert
        Assert.DoesNotThrow(act, "Constructor should not throw any exceptions during initialization.");
        Assert.That(page, Is.Not.Null, "Page instance should be created successfully.");
    }

    /// <summary>
    /// Tests that the StatisticsAndGraphPage constructor sets the datePicker to yesterday's date.
    /// NOTE: This test assumes the datePicker field is accessible. If the field is private
    /// (as generated by XAML), this test will not compile. In that case, this test should be
    /// removed or converted to a UI integration test that verifies the behavior through
    /// the public API or UI automation.
    /// Expected behavior: datePicker.Date should be set to DateTime.Today.AddDays(-1)
    /// </summary>
    [Test]
    [Ignore("This test requires access to the datePicker field which may be private/internal. Enable this test only if the field is accessible, otherwise use UI integration testing.")]
    public void Constructor_WhenCalled_SetsDatePickerToYesterday()
    {
        // Arrange
        DateTime expectedDate = DateTime.Today.AddDays(-1);

        // Act
        var page = new StatisticsAndGraphPage();

        // Assert
        // Uncomment the following line if datePicker is accessible:
        // Assert.That(page.datePicker.Date, Is.EqualTo(expectedDate), "DatePicker should be initialized to yesterday's date (Today - 1 day).");

        Assert.Inconclusive("Unable to verify datePicker.Date without access to the private field. Consider using UI automation or making the field internal with InternalsVisibleTo attribute for testing.");
    }

    /// <summary>
    /// Tests that multiple instances of StatisticsAndGraphPage can be created successfully.
    /// Verifies that the constructor can be called multiple times without side effects or exceptions.
    /// Expected behavior: Each call should create a new, independent instance.
    /// </summary>
    [Test]
    public void Constructor_MultipleInstances_CreatesIndependentInstances()
    {
        // Arrange & Act
        StatisticsAndGraphPage? page1 = null;
        StatisticsAndGraphPage? page2 = null;
        TestDelegate act1 = () => page1 = new StatisticsAndGraphPage();
        TestDelegate act2 = () => page2 = new StatisticsAndGraphPage();

        // Assert
        Assert.DoesNotThrow(act1, "First constructor call should not throw any exceptions.");
        Assert.DoesNotThrow(act2, "Second constructor call should not throw any exceptions.");
        Assert.That(page1, Is.Not.Null, "First page instance should be created successfully.");
        Assert.That(page2, Is.Not.Null, "Second page instance should be created successfully.");
        Assert.That(page1, Is.Not.SameAs(page2), "Each constructor call should create a distinct instance.");
    }

    /// <summary>
    /// Tests that the constructed page is of the correct type and inherits from ContentPage.
    /// Verifies the inheritance hierarchy and type correctness.
    /// Expected behavior: Instance should be assignable to ContentPage.
    /// </summary>
    [Test]
    public void Constructor_WhenCalled_CreatesCorrectType()
    {
        // Arrange & Act
        var page = new StatisticsAndGraphPage();

        // Assert
        Assert.That(page, Is.InstanceOf<StatisticsAndGraphPage>(), "Instance should be of type StatisticsAndGraphPage.");
        Assert.That(page, Is.InstanceOf<ContentPage>(), "Instance should inherit from ContentPage.");
    }
}